"use client"

import { forwardRef } from "react"
import { PDF_THEME_VARS, MUTED_FOREGROUND } from "@/lib/pdf-theme"
import { PdfChannelHeader } from "@/components/pdf-channel-header"
import { PdfChartsSection } from "@/components/pdf-charts-section"
import { PdfCompareSection } from "@/components/pdf-compare-section"
import { PdfVideoTable } from "@/components/pdf-video-table"
import type { ChannelInfo, VideoMetrics, VideoViewDelta } from "@/types"

export interface PdfExportLayoutProps {
  channel: ChannelInfo
  videos: VideoMetrics[]
  rangeVideos: VideoViewDelta[]
  sort: string
  period: string
  rangeStart: string
  rangeEnd: string
  comparisonChannel?: ChannelInfo
  comparisonVideos?: VideoMetrics[]
  comparisonRangeVideos?: VideoViewDelta[]
}

// Build a flat style object from the PDF_THEME_VARS mapping.
// html2canvas reads inline styles on the container, so these override
// the oklch-based CSS custom properties from globals.css.
function buildThemeStyle(): React.CSSProperties & Record<string, string> {
  const style: Record<string, string> = {}
  for (const [key, value] of Object.entries(PDF_THEME_VARS)) {
    style[key] = value
  }
  return style as React.CSSProperties & Record<string, string>
}

export const PdfExportLayout = forwardRef<HTMLDivElement, PdfExportLayoutProps>(
  function PdfExportLayout(
    {
      channel,
      videos,
      rangeVideos,
      sort,
      period,
      rangeStart,
      rangeEnd,
      comparisonChannel,
      comparisonVideos,
      comparisonRangeVideos,
    },
    ref
  ) {
    const isComparing = !!comparisonChannel

    return (
      <div
        ref={ref}
        style={{
          position: "fixed",
          left: -9999,
          top: 0,
          width: 794, // A4 at 96 DPI
          background: "#ffffff",
          color: "#1a1a1a",
          fontFamily: "system-ui, -apple-system, sans-serif",
          fontSize: 13,
          lineHeight: 1.4,
          ...buildThemeStyle(),
        }}
      >
        {/* Header: branding + channel cards + filter context */}
        <div data-section="header" style={{ padding: "16px 20px" }}>
          <PdfChannelHeader
            channel={channel}
            comparisonChannel={comparisonChannel}
            period={period}
            rangeStart={rangeStart}
            rangeEnd={rangeEnd}
            sort={sort}
          />
        </div>

        {/* Charts */}
        {videos.length > 0 && (
          <div data-section="charts" style={{ padding: "8px 20px" }}>
            <PdfChartsSection
              videos={videos}
              comparisonVideos={comparisonVideos}
              primaryName={channel.title}
              comparisonName={comparisonChannel?.title}
              isComparing={isComparing}
            />
          </div>
        )}

        {/* Comparison aggregates */}
        {isComparing && comparisonVideos && comparisonRangeVideos && (
          <div data-section="aggregates" style={{ padding: "8px 20px" }}>
            <PdfCompareSection
              primaryVideos={videos}
              comparisonVideos={comparisonVideos}
              primaryRangeVideos={rangeVideos}
              comparisonRangeVideos={comparisonRangeVideos}
              primaryName={channel.title}
              comparisonName={comparisonChannel!.title}
            />
          </div>
        )}

        {/* Video tables (each chunk is its own data-section for pagination) */}
        <div style={{ padding: "8px 20px" }}>
          <PdfVideoTable
            videos={videos}
            rangeVideos={rangeVideos}
            sort={sort}
            channelName={channel.title}
            isComparing={isComparing}
            comparisonVideos={comparisonVideos}
            comparisonRangeVideos={comparisonRangeVideos}
            comparisonName={comparisonChannel?.title}
          />
        </div>

        {/* Footer */}
        <div
          data-section="footer"
          style={{
            padding: "12px 20px",
            fontSize: 10,
            color: MUTED_FOREGROUND,
            textAlign: "center",
          }}
        >
          Generated by VidMetrics on{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </div>
      </div>
    )
  }
)
